name: Flask CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install flake8
          pip install wheel
          pip install twine
          flake8 --version  # Check if flake8 is properly installed

      - name: Check Python version and installed packages
        run: |
          python --version
          pip list

      - name: Run flake8
        run: python -m flake8 .

      - name: Run tests
        run: pytest

      - name: Build and Publish Artifact
        run: |
            python setup.py sdist bdist_wheel  # Build the package
            # Publish the package to PyPI using the API token
            twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
        env:
            TWINE_USERNAME: _token_
            TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}